/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as StockRouteImport } from './routes/stock'
import { Route as PurchaseOrdersIndexRouteImport } from './routes/purchase-orders.index'
import { Route as PurchaseOrdersPoNumberRouteImport } from './routes/purchase-orders.$poNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersIndexRoute = PurchaseOrdersIndexRouteImport.update({
  id: '/purchase-orders/',
  path: '/purchase-orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersPoNumberRoute = PurchaseOrdersPoNumberRouteImport.update({
  id: '/purchase-orders/$poNumber',
  path: '/purchase-orders/$poNumber',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/stock': typeof StockRoute
  '/purchase-orders/$poNumber': typeof PurchaseOrdersPoNumberRoute
  '/purchase-orders/': typeof PurchaseOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/stock': typeof StockRoute
  '/purchase-orders/$poNumber': typeof PurchaseOrdersPoNumberRoute
  '/purchase-orders': typeof PurchaseOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/stock': typeof StockRoute
  '/purchase-orders/$poNumber': typeof PurchaseOrdersPoNumberRoute
  '/purchase-orders/': typeof PurchaseOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/orders'
    | '/register'
    | '/stock'
    | '/purchase-orders/$poNumber'
    | '/purchase-orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/orders'
    | '/register'
    | '/stock'
    | '/purchase-orders/$poNumber'
    | '/purchase-orders'
  id:
    | '__root__'
    | '/'
    | '/orders'
    | '/register'
    | '/stock'
    | '/purchase-orders/$poNumber'
    | '/purchase-orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrdersRoute: typeof OrdersRoute
  RegisterRoute: typeof RegisterRoute
  StockRoute: typeof StockRoute
  PurchaseOrdersPoNumberRoute: typeof PurchaseOrdersPoNumberRoute
  PurchaseOrdersIndexRoute: typeof PurchaseOrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders/': {
      id: '/purchase-orders/'
      path: '/purchase-orders'
      fullPath: '/purchase-orders/'
      preLoaderRoute: typeof PurchaseOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders/$poNumber': {
      id: '/purchase-orders/$poNumber'
      path: '/purchase-orders/$poNumber'
      fullPath: '/purchase-orders/$poNumber'
      preLoaderRoute: typeof PurchaseOrdersPoNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrdersRoute: OrdersRoute,
  RegisterRoute: RegisterRoute,
  StockRoute: StockRoute,
  PurchaseOrdersPoNumberRoute: PurchaseOrdersPoNumberRoute,
  PurchaseOrdersIndexRoute: PurchaseOrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
