CREATE DATABASE IF NOT EXISTS lh_scm CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS lh_oms CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS lh_as CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
