import type { ScmErrorCode } from '@repo/contracts/scm';
import { defineErrors } from '@repo/nest-kit/api-error';

/** 이 서비스가 내는 에러. 사용: `throw scmError('UNIT_NOT_FOUND', '보조 설명')` */
export const scmError = defineErrors<ScmErrorCode>({
  UNIT_NOT_FOUND: 404,
  UNIT_EVENT_NOT_FOUND: 404,
  UNIT_EVENT_ALREADY_CORRECTED: 409,
  UNKNOWN_LOCATION: 422,
  UNKNOWN_SKU: 422,
  SKU_REQUIRED: 422,
  SERIAL_SKU_MISMATCH: 409,
  DEVICE_REQUEST_NOT_FOUND: 404,
  DEVICE_REQUEST_UNKNOWN_SERIAL: 422,
  QUANTITY_TRACKING_ONLY: 422,
  MOVEMENT_NOT_FOUND: 404,
  MOVEMENT_ALREADY_REVERSED: 409,
  PO_NOT_FOUND: 404,
  PO_NOT_DRAFT: 409,
  PO_NOT_ISSUED: 409,
  PO_ALREADY_CANCELLED: 409,
  PO_HAS_RECEIPTS: 409,
  PO_LINE_NOT_FOUND: 404,
  PO_LINE_ALREADY_CLOSED: 409,
  PO_LINE_CANCELLED: 409,
  PO_LINE_ALREADY_COMPLETE: 409,
  PO_QTY_BELOW_RECEIVED: 409,
  SHIPMENT_NOT_FOUND: 404,
  SHIPMENT_ALREADY_LINKED: 409,
  SHIPMENT_LINES_UNMATCHED: 422,
  SHIPMENT_ALREADY_VOIDED: 409,
});
